# Generated by Django 4.1 on 2022-08-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_day', models.DateTimeField(auto_now_add=True)),
                ('distance_done', models.FloatField()),
            ],
        ),
    ]
